#!/usr/bin/env python3
"""Generate src/words.ts captions for the MultiHopper demo video from
docs/demo-voiceover.txt, WITHOUT a recorded voiceover (placeholder pacing).

Each paragraph in the voiceover maps to a fixed time window aligned to the
shot timeline in src/MultiHopperDemo.tsx. Words are collapsed into comfortable
1-2 word chunks (same chunking rules as casper3643-video/scripts/align_captions.py).
When Yusif records public/voiceover.mp3, re-run align_captions.py (faster-whisper)
to get word-accurate timings and overwrite this file.

Run:  python scripts/make_captions.py
Out:  src/words.ts
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "docs" / "demo-voiceover.txt"
OUT = ROOT / "src" / "words.ts"
FPS = 30.0
MIN_DUR = 0.30

FUNC = {
    "a","an","the","of","to","in","on","at","by","for","from","with","and","but","or",
    "nor","yet","so","as","is","are","was","were","be","been","being","it","its","our",
    "no","not","than","then","that","this","these","those","we","you","he","she","they",
    "them","his","her","their","my","your","i","me","him","us","do","did","does","done",
    "has","had","have","can","could","will","would","shall","should","may","might","must",
    "just","now","here","there","up","down","out","off","over","into","onto","each","every",
    "all","any","some","such","which","who","whom","whose","what","when","where","how","why",
    "if","because","while","once","also","very","too","more","most","much","many","one","two",
    "three","ten","per","via",
}

# Paragraph -> [start, end] seconds, aligned to the shot timeline (11 shots, 10 paragraphs;
# paragraph 10 spans the findings summary + final card).
WINDOWS = [
    (0.4, 10.0),    # title intro
    (10.0, 20.0),   # flow
    (20.0, 33.0),   # happy deploy
    (33.0, 42.0),   # stuck 476
    (42.0, 55.0),   # rescue false promise
    (55.0, 63.0),   # never settles 479
    (63.0, 76.0),   # webhook
    (76.0, 84.0),   # 500 + SQL leak
    (84.0, 91.0),   # amount mismatch
    (91.0, 110.0),  # findings summary + final card
]


def is_func(w: str) -> bool:
    return w.lower().strip(".,;:!?\"'()") in FUNC


def chunk(words):
    """Greedy 1-2 word chunks. Merge a function word with a neighbor."""
    chunks, i, n = [], 0, len(words)
    while i < n:
        w0 = words[i]
        cur = [w0]
        if i + 1 < n:
            w1 = words[i + 1]
            if (is_func(w0["word"]) or is_func(w1["word"])) and not (is_func(w0["word"]) and is_func(w1["word"])):
                cur.append(w1)
                i += 2
            else:
                i += 1
        else:
            i += 1
        chunks.append(cur)
    return chunks


def main():
    text = SRC.read_text(encoding="utf-8")
    paragraphs = [p for p in re.split(r"\n\s*\n", text.strip()) if p.strip()]
    assert len(paragraphs) == len(WINDOWS), f"{len(paragraphs)} paragraphs vs {len(WINDOWS)} windows"

    all_chunks = []
    for para, (t0, t1) in zip(paragraphs, WINDOWS):
        words = re.findall(r"[A-Za-z0-9'’/.-]+", para)
        words = [w for w in words if w.strip()]
        wlist = [{"word": w} for w in words]
        chs = chunk(wlist)
        # distribute chunks evenly across the window, leaving a small tail gap
        span = t1 - t0 - 0.25
        step = span / max(1, len(chs))
        for k, c in enumerate(chs):
            start = round(t0 + k * step, 3)
            dur = round(max(step * 0.92, MIN_DUR), 3)
            all_chunks.append({"start": start, "dur": dur, "text": " ".join(x["word"] for x in c)})

    lines = [
        "// Auto-generated by scripts/make_captions.py (placeholder pacing, no voiceover yet).",
        "// 1-2 word chunks mapped to the shot timeline. Re-run align_captions.py after Yusif",
        "// records public/voiceover.mp3 to get word-accurate faster-whisper timings.",
        f"// {len(all_chunks)} chunks over ~110s of narration.",
        "export const WORDS: { start: number; dur: number; text: string }[] = [",
    ]
    for c in all_chunks:
        t = c["text"].replace('"', '\\"')
        lines.append(f"  {{ start: {c['start']}, dur: {c['dur']}, text: \"{t}\" }},")
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[captions] {len(all_chunks)} chunks -> {OUT}")
    print(f"[captions] first 6: {[c['text'] for c in all_chunks[:6]]}")
    print(f"[captions] last 4: {[c['text'] for c in all_chunks[-4:]]}")


if __name__ == "__main__":
    main()
